### ISSUE TITLE
Error after try

### ISSUE THREAD

**Issue by nndaid** [bdrsmsdn/lucya-bot#4]
![IMG-20201217-WA0210](https://user-images.githubusercontent.com/55502642/102575680-4ceb8c00-4126-11eb-8c40-fe5be774cf63.jpg)

**Comment by bdrsmsdn** [comment]
copynya udah bener?

**Comment by nndaid** [comment]
> copynya udah bener?

Baru aja git clone sc, pas d run kek gtu

**Comment by bdrsmsdn** [comment]
> > copynya udah bener?
> 
> Baru aja git clone sc, pas d run kek gtu

hapus } itunya satu di line 591
